### ISSUE TITLE
Sample project reproducing the (awesome) graphs shown in the readme

### ISSUE THREAD

**Issue by MichaelBechHansen** [knassar/ChartUI#1]
It would be awesome with a demo project reproducing the graphs shown in the README...
That would make the barrier of entry to ChartUI way lower.

**Comment by knassar** [comment]
Each of the main view types (and most of the decorators as well) has an interactive SwiftUI Preview associated with the view file. These are the sources for the animated GIFs shown in the README. Open these in Xcode with a canvas view, and you have an interactive demo.

See: 
- `Sources/ChartUI/Views/Rectangular Charts/LineChart.swift`
- `Sources/ChartUI/Views/Rectangular Charts/BarChart.swift`
- `Sources/ChartUI/Views/Radial Charts/PieChart.swift`
- `Sources/ChartUI/Views/Radial Charts/RingChart.swift`
- `Sources/ChartUI/Views/Rectangular Charts/Interaction/MiniMap.swift`

**Comment by MichaelBechHansen** [comment]
Ah! I see.  That's great.
